---
abstract: 'automate the PhantomJS browser'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Mechanize-PhantomJS
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  HTML::Selector::XPath: 0
  HTTP::Daemon: 0
  HTTP::Response: 0
  LWP::Simple: 0
  Object::Import: 0
  Scalar::Util: 0
  Selenium::Remote::Driver: 0
  perl: 5.006
resources:
  repository: http://github.com/Corion/www-mechanize-phantomjs
version: 0.02
